influxdb:
  image: influxdb:1.8
  container_name: influxdb
  ports:
    - "8086:8086"
  env_file:
    - 'env.influxdb'
  volumes:
    # Data persistency
    # sudo mkdir -p /srv/docker/influxdb/data
    - ./influxdb/data:/root/.influxdb
    - ./influxdb/etc:/etc/influxdb/:ro

grafana:
  image: grafana/grafana:latest
  container_name: grafana
  ports:
    - "3000:3000"
  env_file:
    - 'env.grafana'
  #volumes:
    #- ./grafana:/var/lib/grafana
  links:
    - influxdb
